version: "3.9"

x-python-tmlp:
  &python-tmlp
  image: ruskotwo/emotional-analyzer/python:latest
  environment:
    - TF_ENABLE_ONEDNN_OPTS=0
  env_file:
    - ./config/.env
  profiles: [app]
  networks:
    - emotional-analyzer

services:
  golang:
    image: ruskotwo/emotional-analyzer/golang:latest
    restart: always
    env_file:
      - ./config/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "40001:40001"
      - "3000:3000"
    profiles: [app]
    networks:
      - emotional-analyzer

  python-trainer:
    <<: *python-tmlp
    restart: on-failure
    entrypoint:
      - "python3"
      - "ai/learn.py"
    volumes:
      - .:/var/app
    depends_on:
      rabbitmq:
        condition: service_healthy

  python-workers:
    <<: *python-tmlp
    restart: always
    entrypoint:
      - "supervisord"
      - "-c"
      - "/etc/supervisor/supervisord.conf"
      - "-n"
    volumes:
      - .:/var/app
      - ./ai/supervisor:/etc/supervisor/conf.d
    depends_on:
      rabbitmq:
        condition: service_healthy
      python-trainer:
        condition: service_completed_successfully

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    profiles: [app]
    networks:
      - emotional-analyzer
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 1s
      timeout: 3s
      retries: 5

  mysql:
    image: mysql:8.0.35
    restart: always
    hostname: mysql
#    volumes:
#      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=golang
      - MYSQL_DATABASE=ea
      - MYSQL_USER=golang
      - MYSQL_PASSWORD=golang
    ports:
      - "13306:3306"
    profiles: [app]
    networks:
      - emotional-analyzer
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 5

  telegram-bot:
    image: ruskotwo/emotional-analyzer/telegram-bot:latest
    env_file:
      - ./tests/telegram-bot/.env
    ports:
      - "4000:4000"
    profiles: [tests]
    networks:
      - emotional-analyzer

networks:
  default:
    external: true
    name: emotional-analyzer
  emotional-analyzer:
    name: emotional-analyzer