services:
  golang:
    image: ruskotwo/emotional-analyzer/golang:latest
    env_file:
      - ./config/.env
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - emotional-analyzer

  python:
    image: ruskotwo/emotional-analyzer/python:latest
    entrypoint:
      - "python3"
      - "ai/learn.py"
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0
    env_file:
      - ./config/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/var/app
    networks:
      - emotional-analyzer

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    networks:
      - emotional-analyzer

networks:
  default:
    external: true
    name: emotional-analyzer
  emotional-analyzer:
    name: emotional-analyzer