// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/ruskotwo/emotional-analyzer/internal/config"
	"github.com/ruskotwo/emotional-analyzer/internal/http"
	"github.com/ruskotwo/emotional-analyzer/internal/queue"
)

// Injectors from wire.go:

func InitService() *Service {
	configConfig := config.NewConfig()
	clientImpl := provideRabbitMQ(configConfig)
	names := queue.NewNames(configConfig)
	analysisHandler := http.NewAnalysisHandler(clientImpl, names)
	server := http.NewServer(configConfig, analysisHandler)
	service := NewService(clientImpl, server)
	return service
}
