// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/ruskotwo/emotional-analyzer/internal/config"
	"github.com/ruskotwo/emotional-analyzer/internal/gorm/clients"
	"github.com/ruskotwo/emotional-analyzer/internal/http"
	"github.com/ruskotwo/emotional-analyzer/internal/http/handlers"
	"github.com/ruskotwo/emotional-analyzer/internal/queue"
	"github.com/ruskotwo/emotional-analyzer/internal/queue/workers"
)

// Injectors from wire.go:

func InitService() *Service {
	configConfig := config.NewConfig()
	clientImpl := provideRabbitMQ(configConfig)
	db := provideGormDB(configConfig)
	repository := clients.NewRepository(db)
	sendAnalysisResultWorker := workers.NewSendAnalysisResultWorker(repository)
	workersManager := queue.NewWorkersManager(clientImpl, configConfig, sendAnalysisResultWorker)
	server := provideOAuth2(configConfig)
	analysisHandler := handlers.NewAnalysisHandler(clientImpl, configConfig, server)
	clientsHandler := handlers.NewClientsHandler(configConfig, server, repository)
	oAuthHandler := handlers.NewOAuthHandler(configConfig, server)
	httpServer := http.NewServer(configConfig, analysisHandler, clientsHandler, oAuthHandler)
	service := NewService(workersManager, httpServer)
	return service
}
