POST http://localhost:3000/analyze/task
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "messages": {
    "1": "How are you?",
    "2": "I feel sad",
    "3": "But you can cheer up!",
    "4": "No Im not sure",
    "5": "Ok kill yourself"
  },
  "secret": "secret"
}
